### ISSUE TITLE
As a user I want to be able to access the daily maze game on a web browser, so I can play the game.

### ISSUE THREAD

**Issue by troyphillips** [troyphillips/Daily-Maze-Solver#8]
- [x] Create a web page to host maze
- [x] Display maze on webpage locally
- [x] upload to github and let read the data from json file
- [x] Commit webpage updates to repo
- [x] Add controls to walk in the maze
- [x] check whether the user finished the maze

**Comment by yifan-k** [comment]
New tasks:

- [ ] Add controls to walk in the maze
- [ ] check whether the user finished the maze
